name: LABEL_PR

on:
    pull_request_review:
      types: [submitted]
 

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions: 
        pull-requests: write 
    if: github.event.review.state == 'approved'
    name: job for commenting on PR when approved
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello :wave:, The PR is eligible to merge. It will be automerged if not raised any issues.
          reactions: eyes, rocket
          pr_number: ${{ github.event.pull_request.number }}
          create_if_not_exists: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
  # delete_comment:
  #   runs-on: ubuntu-latest
  #   permissions: 
  #       pull-requests: write 
  #   if: github.event.review.state != 'approved'
  #   name: deleting the comment
  #   steps:
  #       - name: Write a comment that will be deleted at the end of the job
  #         uses: thollander/actions-comment-pull-request@v2
  #         with:
  #           message: |
  #                 The PR is being built...
  #           comment_tag: to_delete
  #           mode: delete
  #           GITHUB_TOKEN: ${{ secrets.ACTIONS }}
  #           pr_number: ${{ github.event.pull_request.number }}

        
