name: label_pr

on:
    pull_request_review:
        types: [submitted]
      
jobs:
    add_labels:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
    
        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
           labels: |
               automerge
           number: ${{ github.event.pull_request.number }}
        