# name: label_pr

# on:
#     pull_request_review:
#         types: [submitted]
      
# jobs:
#     add_labels:
#         runs-on: ubuntu-latest
#         steps:
#         - name: checkout
#           uses: actions/checkout@v2
        
#         - name: find current day
#           id: find_day
#           run: |
#             date1=$(date +"%a")
#             echo "day=$date1" >> "$GITHUB_OUTPUT"
#           shell: bash
    
#         - name: add labels
#           uses: actions-ecosystem/action-add-labels@v1
#           with:
#            labels: |
#                automerge ${{ steps.find_day.outputs.day }}
#            number: ${{ github.event.pull_request.number }}
#            github_token:  ${{ secrets.GITHUB_TOKEN }}

name: label_pr

on:
  pull_request_review:
    types: [submitted]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Print Event Payload
        run: cat $GITHUB_EVENT_PATH

      - name: Run Python Script
        run: |
          pip install requests
          python label_prs.py
        env:
          GITHUB_TOKEN: ${{ secrets.LABEL_TOKEN }}

           
        
